/* Part 12: Anthropology starter deck. Short revision cards: thinkers, tribes, concepts. Written as quick prompts, check them against your own notes. */
window.ANTHRO_DECK = [
  /* ---------- Thinkers ---------- */
  ['Thinkers', 'E. B. Tylor', 'Father of cultural anthropology. Primitive Culture (1871). Culture = "that complex whole". Minimum definition of religion = belief in spiritual beings (animism). Unilineal evolution; doctrine of survivals.'],
  ['Thinkers', 'L. H. Morgan', 'Ancient Society (1877). Savagery, barbarism, civilization, each with lower, middle and upper stages. Studied the Iroquois; Systems of Consanguinity and Affinity (classificatory vs descriptive kinship).'],
  ['Thinkers', 'J. G. Frazer', 'The Golden Bough. Magic, then religion, then science. Sympathetic magic: homeopathic (law of similarity) and contagious (law of contact).'],
  ['Thinkers', 'Franz Boas', 'Historical particularism, cultural relativism, four-field approach. Rejected unilineal evolution and race-culture links. Fieldwork with the Kwakiutl.'],
  ['Thinkers', 'Bronisław Malinowski', 'Functionalism (needs-based). Trobriand Islands fieldwork, participant observation. Argonauts of the Western Pacific; Kula ring.'],
  ['Thinkers', 'A. R. Radcliffe-Brown', 'Structural-functionalism: society as a system, institutions serve social structure. The Andaman Islanders. Joking relationships, avunculate.'],
  ['Thinkers', 'E. E. Evans-Pritchard', 'The Nuer (segmentary lineage system). Witchcraft, Oracles and Magic among the Azande. Said anthropology is closer to history than to natural science.'],
  ['Thinkers', 'Claude Lévi-Strauss', 'Structuralism. Binary oppositions, myths as structures of the mind. Alliance theory in Elementary Structures of Kinship. The Raw and the Cooked.'],
  ['Thinkers', 'Edmund Leach', 'Political Systems of Highland Burma (Kachin: gumsa and gumlao). Critic of rigid structural-functionalism; showed systems oscillate.'],
  ['Thinkers', 'Clifford Geertz', 'Interpretive anthropology. Thick description. Religion as a cultural system. The Balinese cockfight.'],
  ['Thinkers', 'Leslie White', 'Neo-evolutionism and culturology. Culture advances with energy harnessed per capita per year. The Evolution of Culture.'],
  ['Thinkers', 'Julian Steward', 'Cultural ecology and multilinear evolution. Culture core = features tied to subsistence and economy.'],
  ['Thinkers', 'Marvin Harris', 'Cultural materialism: infrastructure shapes structure and superstructure. Explained India\'s sacred cow in ecological terms.'],
  ['Thinkers', 'Marcel Mauss', 'The Gift: gift giving as a total social fact built on obligations to give, receive and reciprocate.'],
  ['Thinkers', 'Émile Durkheim', 'Social facts. Mechanical vs organic solidarity. Elementary Forms of the Religious Life: sacred vs profane, totemism as the origin of religion.'],
  ['Thinkers', 'Victor Turner', 'Symbolic anthropology among the Ndembu. Liminality and communitas. Extended Van Gennep on rites of passage.'],
  ['Thinkers', 'Arnold van Gennep', 'The Rites of Passage: separation, transition (liminal), incorporation.'],
  ['Thinkers', 'Ruth Benedict', 'Patterns of Culture. Apollonian and Dionysian cultures. Culture and personality school.'],
  ['Thinkers', 'Margaret Mead', 'Coming of Age in Samoa. Sex and Temperament in Three Primitive Societies. Culture shapes gender roles.'],
  ['Thinkers', 'Robert Redfield', 'Great tradition and little tradition. Folk-urban continuum. Studied Tepoztlán.'],
  ['Thinkers', 'A. L. Kroeber', 'Culture area concept, the superorganic, culture as a level above the organic.'],
  ['Thinkers', 'M. N. Srinivas', 'Sanskritization, Westernization, dominant caste. Religion and Society among the Coorgs. Village studies (Rampura).'],
  ['Thinkers', 'Louis Dumont', 'Homo Hierarchicus. Caste as a system of hierarchy based on purity and pollution.'],
  ['Thinkers', 'G. S. Ghurye', 'Caste and Race in India. Called tribals "backward Hindus". Father of Indian sociology.'],
  ['Thinkers', 'Verrier Elwin', 'The Baiga, The Muria and their Ghotul. Favoured protecting tribal identity (isolation / "national park" view). Advised on the tribal Panchsheel.'],
  ['Thinkers', 'S. C. Roy', 'Founder of Indian ethnography. The Mundas and their Country, The Oraons of Chotanagpur. Founded the journal Man in India.'],
  ['Thinkers', 'L. P. Vidyarthi', 'The Sacred Complex of Kashi. Nature-Man-Spirit complex among tribes. Studied Maler of Rajmahal hills.'],
  ['Thinkers', 'Surajit Sinha', 'Tribe-caste continuum; studied tribes in their civilizational context, and Rajput-myth state formation among the Bhumij.'],
  ['Thinkers', 'B. S. Guha', 'Racial classification of India into six main types (1931, based on the 1931 Census data). Later directed the Anthropological Survey of India.'],
  ['Thinkers', 'McKim Marriott', 'Universalization and parochialization in village Hinduism (Kishan Garhi). Great and little traditions.'],
  /* ---------- Tribes ---------- */
  ['Tribes', 'Santhal', 'Largest Indian tribe in the east (Jharkhand, West Bengal, Odisha, Bihar, Assam). Santali, Austroasiatic family, Ol Chiki script. Santhal Hul rebellion 1855.'],
  ['Tribes', 'Gond', 'Central India (MP, Chhattisgarh, Maharashtra, Odisha, Telangana). Dravidian speakers, one of the largest tribes. The Muria sub-group is famous for the ghotul.'],
  ['Tribes', 'Bhil', 'Western India (Rajasthan, Gujarat, MP, Maharashtra). Bhili language. Bhagoria festival, expert archers.'],
  ['Tribes', 'Munda', 'Chotanagpur. Khuntkatti land system. Birsa Munda and the Ulgulan rebellion (1899-1900). Mundari, Austroasiatic.'],
  ['Tribes', 'Oraon (Kurukh)', 'Chotanagpur. Dravidian language Kurukh. Dhumkuria bachelors\' dormitory. Studied by S. C. Roy.'],
  ['Tribes', 'Toda', 'Nilgiri hills. Buffalo pastoralists with dairy temples. Fraternal polyandry in older accounts. Studied by W. H. R. Rivers.'],
  ['Tribes', 'Khasi', 'Meghalaya. Matrilineal, youngest daughter (khatduh) inherits the ancestral property. Austroasiatic (Mon-Khmer).'],
  ['Tribes', 'Garo', 'Meghalaya. Matrilineal, Tibeto-Burman. Nokma, the female heir, and her husband manage the land.'],
  ['Tribes', 'Naga tribes', 'Nagaland and neighbours. Many tribes (Angami, Ao, Konyak, Sema, Lotha...). Morung dormitories; historical headhunting among some groups.'],
  ['Tribes', 'Apatani', 'Arunachal Pradesh (Ziro valley). Wet rice and fish cultivation without animals or machines. Traditional facial tattoos and nose plugs on older women.'],
  ['Tribes', 'Baiga', 'Madhya Pradesh and Chhattisgarh. PVTG. Bewar (shifting cultivation). Studied by Verrier Elwin.'],
  ['Tribes', 'Chenchu', 'Andhra Pradesh and Telangana (Nallamala). PVTG. Hunting and gathering forest foragers.'],
  ['Tribes', 'Irula', 'Tamil Nadu and Kerala. Known for snake and rat catching, forest knowledge.'],
  ['Tribes', 'Dongria Kondh', 'Odisha (Niyamgiri hills). PVTG. Their hill is sacred (Niyam Raja); the bauxite mining conflict.'],
  ['Tribes', 'Bondo', 'Odisha (Malkangiri). PVTG. Austroasiatic. Known for distinctive dress and ornaments.'],
  ['Tribes', 'Andaman tribes', 'Great Andamanese, Jarawa, Onge, Sentinelese are Negrito groups; Shompen of Great Nicobar are Mongoloid. All are PVTGs; contact is restricted.'],
  ['Tribes', 'Gaddi', 'Himachal Pradesh. Transhumant pastoralists (sheep, goat) who move between summer and winter pastures.'],
  ['Tribes', 'Gujjar Bakarwal', 'Jammu and Kashmir. Transhumant, nomadic pastoralists.'],
  ['Tribes', 'Siddi', 'Karnataka, Gujarat, Hyderabad. Groups of African descent, now a Scheduled Tribe in several states.'],
  /* ---------- Concepts ---------- */
  ['Concepts', 'Enculturation vs acculturation', 'Enculturation: learning your own culture. Acculturation: change when two cultures are in continuous contact.'],
  ['Concepts', 'Cultural relativism', 'Judge a culture by its own standards, not by another\'s. Associated with Boas. Opposite of ethnocentrism.'],
  ['Concepts', 'Emic vs etic', 'Emic: the insider\'s view of meanings. Etic: the outside observer\'s analytic view. Term from Kenneth Pike; developed by Marvin Harris.'],
  ['Concepts', 'Participant observation', 'Living with the community and observing from the inside. Developed by Malinowski.'],
  ['Concepts', 'Diffusion', 'Spread of cultural traits between societies. Schools: British diffusionism (Elliot Smith, Perry), German kulturkreis, American culture area.'],
  ['Concepts', 'Cultural lag', 'William Ogburn: material culture changes faster than non-material culture, leaving a gap.'],
  ['Concepts', 'Descent systems', 'Patrilineal, matrilineal, double, bilateral and ambilineal descent. Lineage, clan, phratry, moiety are descent groups of increasing size.'],
  ['Concepts', 'Types of marriage', 'Endogamy, exogamy, monogamy, polygyny, polyandry, levirate (marry deceased husband\'s brother), sororate (marry deceased wife\'s sister).'],
  ['Concepts', 'Cross vs parallel cousins', 'Cross cousins: children of siblings of the opposite sex. Parallel cousins: children of siblings of the same sex. Cross-cousin marriage is preferred in many societies.'],
  ['Concepts', 'Avunculate and couvade', 'Avunculate: special bond with the mother\'s brother. Couvade: husband imitates childbirth practices at his wife\'s delivery.'],
  ['Concepts', 'Totem and taboo', 'Totem: a sacred natural object linked to a clan. Taboo: a sacred prohibition. Freud, Durkheim, Radcliffe-Brown all wrote on them.'],
  ['Concepts', 'Animism, animatism, mana', 'Animism (Tylor): belief in spirit beings. Animatism (Marett): impersonal supernatural force, mana.'],
  ['Concepts', 'Magic vs religion', 'Magic coerces supernatural powers by technique. Religion appeals to them by worship. Frazer, Malinowski, Durkheim differ on the link.'],
  ['Concepts', 'Rites of passage', 'Van Gennep: rituals marking status change in three phases: separation, liminality, incorporation.'],
  ['Concepts', 'Reciprocity (Sahlins)', 'Generalized, balanced and negative reciprocity, ranging from close kin to strangers.'],
  ['Concepts', 'Jajmani system', 'Hereditary exchange of goods and services between landowning patrons (jajmans) and service castes in Indian villages. William Wiser.'],
  ['Concepts', 'Sanskritization', 'M. N. Srinivas: a lower caste or tribe adopts the customs and ritual of a higher, usually twice-born, caste to rise in the hierarchy.'],
  ['Concepts', 'Dominant caste', 'Srinivas: a numerically strong, land-owning, locally powerful caste that is not necessarily ritually high.'],
  ['Concepts', 'Tribe-caste continuum', 'Surajit Sinha and others: tribes and castes are not sharply separate, but points on a continuum of Hindu integration.'],
  ['Concepts', 'Approaches to tribal development', 'Isolation (Elwin\'s earlier view), assimilation (Ghurye), integration (Nehru\'s tribal Panchsheel).'],
  ['Concepts', 'PVTG criteria', 'Pre-agricultural level of technology, declining or stagnant population, very low literacy, subsistence economy. 75 groups are recognised as PVTGs.'],
  ['Concepts', 'Fifth and Sixth Schedules', 'Fifth: administration of Scheduled Areas in most states (Governor, Tribes Advisory Council). Sixth: Autonomous District and Regional Councils in Assam, Meghalaya, Tripura, Mizoram.'],
  ['Concepts', 'PESA and Forest Rights Act', 'PESA 1996: extends Panchayats to Scheduled Areas, Gram Sabha powers. Forest Rights Act 2006: recognises individual and community forest rights of forest dwellers.'],
  ['Concepts', 'Article 342', 'The President notifies which communities are Scheduled Tribes. Article 46 directs the State to promote their educational and economic interests.'],
  ['Concepts', 'Race: classical and modern view', 'Race is a biological classification of limited use; modern anthropology sees more variation within than between populations. Racial classification of India: Risley, Guha.'],
  ['Concepts', 'Cultural ecology', 'Steward: how culture adapts to its environment through the culture core. Compare with White\'s energy theory.'],
  ['Concepts', 'Thick description', 'Geertz (from Gilbert Ryle): explaining behaviour with its layered meanings, not just reporting it.'],
  ['Concepts', 'Liminality and communitas', 'Turner: the in-between stage of ritual; people there form an egalitarian bond called communitas.'],
];
